# docker-compose.yml for mongodb
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      # set MONGO_USER and MONGO_PASS environment variables
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
