version: '3'
services:
  redis:
      image: redis:3.2-alpine
      restart: always

      # expose port to the host machine
      ports:
        - 6379:6379

      # mount redis data to the host folder
      volumes:
        - $PWD/redis-data:/data

      # get redis password from environment variable REDIS_PASSWORD
      # appendonly flag is used to persist redis data over restarts and container stops and starts
      command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
